### ISSUE TITLE
Drag speed and resize speed has high latency

### ISSUE THREAD

**Issue by mrkita** [dmarcotte/easy-move-resize#26]
I just switching to using OSX from Windows, and was looking for a replacement for ALTDRAG.

At work am hooked up to a 1920x1080 external monitor and extending my desktop, this seems to work great.

However, I work often mostly from home, and there I am using a 4k 43" Phillips monitor together with a logitech bluetooth mouse. With that setup the program responds extremely slowly when I attempt to drag or resize a window, or rather it trails behind the mouse cursor position. It does not matter if I am doing this for a window on the MacBook display or the external monitor.

If I switch to using the track pad with the same monitor setup, the problem still occurs for windows on my external monitor, BUT NOT for windows hosted on my Macbook.

I assume this has something to do with position and scaling... let me know if more info is needed.

**Comment by dmarcotte** [comment]
Thanks @mrkita.  The density of that display may be resulting in us doing too many calculations along the mouse path.  Will have a look.

**Comment by jonathanwalter** [comment]
I have the same problem... But I only have one 24" 1920x1080 monitor and it affects almost all apps. The only exception I've found (so far) is MacVim which is almost fast enough but very "choppy". This is on macOS 10.12.5. It worked perfect on 10.11.x. Makes me regret I upgraded... :(

I'd be happy to assist in any testing or if you need any more info!

**Comment by xdmx** [comment]
I've just installed it on a brand new mac (2015) with sierra 15" and I can definitely see the latency when I quickly resize the windows. I don't see any latency when I move them around.

This is on the mac itself, without any external monitor and with plenty of memory and cpu available (I've closed all programs)

**Comment by dmarcotte** [comment]
Thanks folks.  I poked at the event filtering we do, and it's likely we can smarten it up a bit.  

To help with that: is the lag apparent on _all_ apps on your high DPI displays?

Or just certain apps?  And if yes, which ones?  I know that Microsoft Office apps are dog slow on resize.  Any others you can call out as specifically problematic to give me more things to troubleshoot against?

**Comment by jonathanwalter** [comment]
So I got a new mouse (Master MX 2S) and this made the problem almost disappear! Now it's a little bit slow at times but totally usable. No idea why.

I do not have any high DPI monitor, but it does/did affect _all_ apps.

**Comment by dmarcotte** [comment]
Very interesting, thanks @jonathanwalter.

**Comment by xdmx** [comment]
For me is mostly on specific apps, for what I've experienced so far. Especially when I resize big apps, like Firefox and Atom, but it seems working without any delay for smaller apps like the mac text editor.

**Comment by albertferras** [comment]
Same here, if the app is fast at redrawing it's content then the resize is okay. If the app is slow at redrawing, then a there's a lot of delay when moving/resizing the window.

**Comment by mrkita** [comment]
For me it is ALL apps from what I remember, but I am not currently at home to test it.

I am using a MX Master at home... maybe it has something to do with it? I will try my magic mouse on Friday with my 4k monitor on Friday and see.

**Comment by mrkita** [comment]
Ok tested this morning and... it does seem to be related to the mouse. My magic mouse does not have the same problem, although on my high DPI 4k monitor, it is somehow a bit slow.

If I switch to my Logitech MX master the problem is immediate as before. That is unfortunate as I love this mouse... any ideas?

**Comment by mrkita** [comment]
Ok for me, it appears to be a very strange interaction with bluetooth/my logitech MX Master mouse.

I switched to using the Logitech unifying receive for making the connection with my Mac, and suddenly Easy Move & Resize works reliably on both my large high dpi screen and MacBookPro.

That was the only difference I made

**Comment by friederbluemle** [comment]
I'm having the same issue. Extremely slow response (window lags behind mouse movement by 1-2 seconds) Using latest macOS 10.13 High Sierra, with a HiDPI screen and Logitech G600 mouse.

**Comment by albertferras** [comment]
I think that if people are seeing improvements when they change their mouse then it means the OS is receiving less or more often updates on the cursor position, therefore EasyMoveResize gets triggered more often, which requests more screen re-draws.

Would it be possible to not "listen" to mouse position changes so often and do it only every X millis? Or maybe even not resize app if mouse didn't move at all (I guess that's already done...)

**Comment by sebastienvermeille** [comment]
Same here ... it make it pretty not usable :/

**Comment by dmarcotte** [comment]
Thanks for all the info everyone.  This _should_ be resolved by https://github.com/dmarcotte/easy-move-resize/pull/31 (:thumbsup: "every X millis" @albertferras).  Let me know if you see otherwise.

Try it out in this release: https://github.com/dmarcotte/easy-move-resize/releases/tag/1.2.0

**Comment by friederbluemle** [comment]
Works perfectly!!! Thanks @dmarcotte 👍 
🎉 🎉 🎉

**Comment by albertferras** [comment]
much better 👍 

the only thing that is still not perfect is that the resizing's "frames(renders) per second" is a bit too low. Maybe it could be increased a bit.
Probably this will depend on each computer, so would be good if we could manually configure the refresh delay ourselves within the app ;)

**Comment by dmarcotte** [comment]
Thanks for reporting back @friederbluemle, @albertferras.  Glad things are improved!

As for the frames per second sometimes feeling a bit low, I've opened an issue to keep our eyes on possible improving this in the future: https://github.com/dmarcotte/easy-move-resize/issues/33

**Comment by sebastienvermeille** [comment]
It works great ! 👍
